name: CI and Publish Contracts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to check OpenAPI spec is up-to-date
  check-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Generate OpenAPI
        run: npm run gen:openapi
      - name: Check OpenAPI diff
        run: |
          if ! git diff --exit-code openapi.json; then
            echo "\033[0;31mERROR: openapi.json není aktuální. Spusťte 'npm run gen:openapi' a commitněte změny.\033[0m"
            exit 1
          fi

  # Job to run the Continuous Integration pipeline
  continuous-integration:
    needs: check-openapi
    uses: sparesparrow/mcp-prompts/.github/workflows/reusable-ts-ci.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Job to publish the package if CI is successful and the trigger is a push to main
  publish-package:
    needs: continuous-integration
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: sparesparrow/mcp-prompts/.github/workflows/reusable-publish.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 